---
version: '0.1'
services:
  api:
    #image: 06ampolleta/haiyaexe:latest
    image: 06ampolleta/vaiyaexe:latest
    restart:  always
    container_name: api
    ports:
      #- "5000:80"
      - "5000:5000"
    environment:
      - "API_WORKERS=2"
