
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: api
  labels:
    app.kubernetes.io/framework: app
    app.kubernetes.io/component: core
    app.kubernetes.io/name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/framework: app
      app.kubernetes.io/component: core
      app.kubernetes.io/name: api
  template:
    metadata:
      labels:
        app.kubernetes.io/framework: app
        app.kubernetes.io/component: core
        app.kubernetes.io/name: api
    spec:
      containers:
      - name: api
        image: 06ampolleta/haiyaexe:latest
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          httpGet:
            path: /hello
            port: 5000
            httpHeaders:
              - name: content-type
                value: application/json
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
            add:
              - MKNOD
              - CHOWN
              - SETGID
              - SETUID
              - SYS_CHROOT
        volumeMounts:
          - mountPath: /tmp
            name: tmp-storage
            readOnly: false
          - mountPath: /run/haproxy
            name: var-run-storage
            readOnly: false
        env:
          - name: API_WORKERS
            value: "2"
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
        - emptyDir: {}
          name: tmp-storage
        - emptyDir: {}
          name: var-run-storage
