
---
apiVersion: v1
kind: Service
metadata:
  namespace: api
  name: http
spec:
  selector:
    app.kubernetes.io/framework: app
    app.kubernetes.io/component: core
    app.kubernetes.io/name: api
  ports:
  - name: api
    protocol: TCP
    port: 5000
    targetPort: 5000
  - name: exporter
    protocol: TCP
    port: 5001
    targetPort: 5001
