
---
apiVersion: v1
kind: Service
metadata:
  namespace: api
  name: api-deployment-service
  annotations:
    metallb.universe.tf/address-pool: production-public-ips
spec:
  selector:
    app: api
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer
