
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: prometheu
spec:
  selector:
    app.kubernetes.io/framework: monitoring
    app.kubernetes.io/component: core
    app.kubernetes.io/name: prometheus
  ports:
  - name: http
    protocol: TCP
    port: 9090
    targetPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: grafana
spec:
  selector:
    app.kubernetes.io/framework: monitoring
    app.kubernetes.io/component: core
    app.kubernetes.io/name: grafana
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
