
---
apiVersion: v1
kind: Pod
metadata:
  name: tester
  namespace: api
spec:
  containers:
  - name: tester
    stdin: true
    tty: true
    image: kalilinux/kali-rolling
    imagePullPolicy: Always
    livenessProbe:
      initialDelaySeconds: 1
      periodSeconds: 5
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 1
      exec:
        command:
          - cat
          - /etc/security/opasswd
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 40m
        memory: 40Mi
  nodeSelector:
    kubernetes.io/os: linux
