
---
apiVersion: v1
kind: Namespace
metadata:
  name: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: api
  labels:
    app: api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        #image: 06ampolleta/haiyaexe:latest # with haproxy
        image: 06ampolleta/vaiyaexe:latest # without haproxy
        ports:
        # - containerPort: 80   # with haproxy
        - containerPort: 5000 # without haproxy
        env:
          - name: API_WORKERS
            value: "2"
---
apiVersion: v1
kind: Service
metadata:
  namespace: api
  name: api-deployment-service
  annotations:
    metallb.universe.tf/address-pool: production-public-ips
spec:
  selector:
    app: api
  ports:
    # - port: 80 # with haproxy
    - port: 5000 # without haproxy
      targetPort: 5000
  type: LoadBalancer
