{
 "title": "Hello World",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Current Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "haproxy_backend_current_sessions",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connect Time Average",
   "type": "timeseries",
   "description": "haproxy_backend_connect_time_average_seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "haproxy_backend_connect_time_average_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http requests",
   "type": "timeseries",
   "description": "haproxy_backend_http_requests_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "haproxy_backend_http_requests_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "description": "haproxy_backend_response_time_average_seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "haproxy_backend_response_time_average_seconds",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}